# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

use_frameworks!

target 'AppArel' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  swift_version = '3.0'
  # Pods for AppArel

  pod 'SQLite.swift', '~> 0.11.2'
  pod 'FontAwesome.swift'

  target 'AppArelTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AppArelUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
